config:
    receivers:
      # Data sources: traces, metrics, logs
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318


    processors:
      # Data sources: traces, metrics, logs
      batch:
        send_batch_max_size: 10000
        timeout: 10s
      memory_limiter:
        check_interval: 5s
        limit_mib: 4000
        spike_limit_mib: 500

    exporters:
      logging:
        verbosity: detailed
      prometheusremotewrite:
        endpoint: http://prometheus-kube-prometheus-prometheus.prometheus-system.svc.cluster.local:9090/api/v1/write
        remote_write_queue:
          enabled: true
        tls:
          insecure: true
      prometheus:
        endpoint: '0.0.0.0:8889'
      #otlp/jaeger:
      #  endpoint: http://jaeger-collector.jaeger-system.svc.cluster.local:4317
      #  tls:
      #    insecure: true
      loki:
        endpoint: http://loki.loki-system.svc.cluster.local:3100/loki/api/v1/push

    service:
      pipelines:
        metrics:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
           - prometheusremotewrite
           - prometheus
        #traces:
        #  receivers:
        #    - otlp
        #  processors:
        #    - memory_limiter
        #    - batch
        #  exporters:
        #   - otlp/jaeger
        logs:
          receivers:
            - filelog
          processors:
            - memory_limiter
            - batch
          exporters:
           - loki
           - logging